name = "espidf"
version = "0.2.0-dev"
website = "https://github.com/godunko/espidf"
description = "Ada/ESP-IDF"
long-description = """
This is the base crate for Ada bindings to the ESP-IDF (Espressif IoT Development Framework).
It provides the foundational type definitions and root package hierarchy required to build Ada applications for Espressif SoC platforms.
"""

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded", "esp32", "espidf"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_base = "*"
