name = "espidf"
version = "0.2.0-dev"
website = "https://github.com/godunko/espidf"
description = "Ada/ESP-IDF bindings"
long-description = """
Base package for the ESP-IDF Ada bindings, providing foundational type definitions and the root hierarchy for Ada applications on Espressif microcontrollers.
"""

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded", "esp32", "espidf"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_base = "*"
